'use client'

import { useCallback, useEffect, useState } from 'react'

import {
  getAllRecords,
  getPendingSyncRecords,
  addRecord,
  putRecord,
  removeRecord,
} from '@/lib/db'
import type { Record, RecordInsert, RecordUpdate } from '@/types/record'
import { dateToTimestamptz } from '@/lib/date-handle'
import {
  syncCreateToCalendar,
  syncUpdateToCalendar,
  syncDeleteFromCalendar,
  syncFetchCalendarEvents,
} from '@/app/actions/calendar'

type FilterParams = {
  search?: string
  from?: string
  to?: string
}

export function useRecords(isSignedIn = false) {
  const [records, setRecords] = useState<Record[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [pendingSyncCount, setPendingSyncCount] = useState(0)

  const loadRecords = useCallback(async () => {
    setIsLoading(true)
    try {
      const todayEnd = new Date()
      todayEnd.setHours(23, 59, 59, 999)
      
      const allLocalRaw = await getAllRecords()
      // Rule: Only show records from today or earlier
      const allLocal = allLocalRaw.filter((r) => new Date(r.date) <= todayEnd)
      let finalRecords = [...allLocal]

      if (isSignedIn) {
        const timeMax = todayEnd.toISOString()
        const result = await syncFetchCalendarEvents(undefined, timeMax)
        if ('events' in result) {
          const calendarEvents = result.events
          const localByEventId = new Map(
            allLocal.filter((r) => r.googleCalendarEventId).map((r) => [r.googleCalendarEventId, r])
          )
          
          const calendarEventIds = new Set<string>()
          const mergedRecords: Record[] = []
          const toUpdateLocal: Record[] = []

          // 1. Process all active Google Calendar events
          for (const ev of calendarEvents) {
            calendarEventIds.add(ev.id)
            const local = localByEventId.get(ev.id)
            if (local) {
              // Override local fields with GC source of truth
              mergedRecords.push({
                ...local,
                title: ev.title,
                description: ev.description,
                date: ev.date,
                isAutoGenerated: ev.isAutoGenerated,
                syncPending: false,
              })
            } else {
              // Create temporary local representation for GC-only events
              mergedRecords.push({
                id: `calendar-${ev.id}`,
                title: ev.title,
                description: ev.description,
                category: 'Personal', // Fallback category for remote events
                date: ev.date,
                createdAt: ev.date,
                googleCalendarEventId: ev.id,
                isAutoGenerated: ev.isAutoGenerated,
                syncPending: false,
              })
            }
          }

          // 2. Process local records ensuring proper sync states
          for (const local of allLocal) {
            if (!local.googleCalendarEventId) {
              if (!local.syncPending) {
                const fixed = { ...local, syncPending: true }
                toUpdateLocal.push(fixed)
                mergedRecords.push(fixed)
              } else {
                mergedRecords.push(local)
              }
            } else if (!calendarEventIds.has(local.googleCalendarEventId)) {
              // Self-heal: Record was deleted from Calendar remotely
              const fixed = { ...local, syncPending: true, googleCalendarEventId: null }
              toUpdateLocal.push(fixed)
              mergedRecords.push(fixed)
            }
          }

          // Fire and forget self-healing DB updates
          if (toUpdateLocal.length > 0) {
            Promise.all(toUpdateLocal.map((r) => putRecord(r))).catch(console.error)
          }

          finalRecords = mergedRecords
        }
      }

      finalRecords.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
      setRecords(finalRecords)

      const pending = isSignedIn 
        ? finalRecords.filter((r) => r.syncPending === true) 
        : []
      setPendingSyncCount(pending.length)
    } catch (error) {
      console.error('Error loading records', error)
    } finally {
      setIsLoading(false)
    }
  }, [isSignedIn])

  useEffect(() => {
    loadRecords()
  }, [loadRecords])

  const createRecord = useCallback(
    async (data: RecordInsert) => {
      const newRecord: Record = {
        ...data,
        id:
          typeof crypto !== 'undefined' && crypto.randomUUID
            ? crypto.randomUUID()
            : Math.random().toString(36).substring(2, 15) +
              Date.now().toString(36),
        createdAt: dateToTimestamptz(new Date()),
        googleCalendarEventId: null,
        syncPending: false,
      }

      if (isSignedIn) {
        const result = await syncCreateToCalendar({
          title: newRecord.title,
          description: newRecord.description,
          date: newRecord.date,
        })
        if ('eventId' in result) {
          newRecord.googleCalendarEventId = result.eventId
          newRecord.syncPending = false
        } else {
          newRecord.syncPending = true
        }
      }

      await addRecord(newRecord)
      await loadRecords()
      return newRecord
    },
    [isSignedIn, loadRecords]
  )

  const updateRecord = useCallback(
    async (data: RecordUpdate) => {
      const all = await getAllRecords()
      const existing = all.find((r) => r.id === data.id)
      if (!existing) throw new Error('Record not found')

      const updated: Record = {
        ...existing,
        ...data,
        updatedAt: dateToTimestamptz(new Date()),
      }

      if (isSignedIn) {
        if (updated.googleCalendarEventId) {
          const result = await syncUpdateToCalendar(
            updated.googleCalendarEventId,
            {
              title: updated.title,
              description: updated.description,
              date: updated.date,
            }
          )
          updated.syncPending = 'error' in result
        } else {
          // No previous event — try to create one now
          const result = await syncCreateToCalendar({
            title: updated.title,
            description: updated.description,
            date: updated.date,
          })
          if ('eventId' in result) {
            updated.googleCalendarEventId = result.eventId
            updated.syncPending = false
          } else {
            updated.syncPending = true
          }
        }
      }

      await putRecord(updated)
      await loadRecords()
      return updated
    },
    [isSignedIn, loadRecords]
  )

  const deleteRecord = useCallback(
    async (id: string) => {
      if (isSignedIn) {
        const all = await getAllRecords()
        const existing = all.find((r) => r.id === id)
        if (existing?.googleCalendarEventId) {
          // Best-effort delete from calendar; if it fails we still remove locally
          await syncDeleteFromCalendar(existing.googleCalendarEventId).catch(
            (e) => console.warn('[deleteRecord] calendar sync failed', e)
          )
        }
      }
      await removeRecord(id)
      await loadRecords()
    },
    [isSignedIn, loadRecords]
  )

  const retryPendingSync = useCallback(async () => {
    if (!isSignedIn) return { synced: 0, failed: 0 }
    const pending = await getPendingSyncRecords()
    let synced = 0
    let failed = 0

    for (const record of pending) {
      try {
        let result: { eventId: string } | { error: string } | { success: true }
        if (record.googleCalendarEventId) {
          result = await syncUpdateToCalendar(record.googleCalendarEventId, {
            title: record.title,
            description: record.description,
            date: record.date,
          })
        } else {
          result = await syncCreateToCalendar({
            title: record.title,
            description: record.description,
            date: record.date,
          })
        }

        if ('eventId' in result) {
          await putRecord({
            ...record,
            googleCalendarEventId: result.eventId,
            syncPending: false,
          })
          synced++
        } else if ('success' in result) {
          await putRecord({ ...record, syncPending: false })
          synced++
        } else {
          failed++
        }
      } catch {
        failed++
      }
    }

    await loadRecords()
    return { synced, failed }
  }, [isSignedIn, loadRecords])

  const dismissPendingSync = useCallback(
    async (id: string) => {
      const all = await getAllRecords()
      const record = all.find((r) => r.id === id)
      if (!record) return
      await putRecord({ ...record, syncPending: false })
      await loadRecords()
    },
    [loadRecords]
  )

  const filterRecords = useCallback(
    (params: FilterParams) => {
      return records.filter((record) => {
        const recordDate = new Date(record.date)

        if (params.search) {
          const search = params.search.toLowerCase()
          if (!record.title.toLowerCase().includes(search)) return false
        }

        if (params.from) {
          const fromDate = new Date(params.from)
          fromDate.setHours(0, 0, 0, 0)
          if (recordDate < fromDate) return false
        }

        if (params.to) {
          const toDate = new Date(params.to)
          toDate.setHours(23, 59, 59, 999)
          if (recordDate > toDate) return false
        }

        return true
      })
    },
    [records]
  )

  return {
    records,
    isLoading,
    pendingSyncCount,
    createRecord,
    updateRecord,
    deleteRecord,
    filterRecords,
    retryPendingSync,
    dismissPendingSync,
  }
}
