'use server'

import { auth } from '@/auth'
import {
  createCalendarEvent,
  updateCalendarEvent,
  deleteCalendarEvent,
  fetchCalendarEvents,
  type CalendarEventInput,
} from '@/lib/google-calendar'

export type SimpleCalendarEvent = {
  id: string
  title: string
  description?: string | null
  date: string
  isAutoGenerated?: boolean
}

async function getAccessToken(): Promise<string | null> {
  const session = await auth()
  return (session as { accessToken?: string })?.accessToken ?? null
}

export async function syncCreateToCalendar(
  input: CalendarEventInput
): Promise<{ eventId: string } | { error: string }> {
  try {
    const accessToken = await getAccessToken()
    if (!accessToken) return { error: 'No access token' }
    const eventId = await createCalendarEvent(accessToken, input)
    return { eventId }
  } catch (err) {
    console.error('[syncCreateToCalendar]', err)
    return { error: String(err) }
  }
}

export async function syncUpdateToCalendar(
  eventId: string,
  input: CalendarEventInput
): Promise<{ success: true } | { error: string }> {
  try {
    const accessToken = await getAccessToken()
    if (!accessToken) return { error: 'No access token' }
    await updateCalendarEvent(accessToken, eventId, input)
    return { success: true }
  } catch (err) {
    console.error('[syncUpdateToCalendar]', err)
    return { error: String(err) }
  }
}

export async function syncDeleteFromCalendar(
  eventId: string
): Promise<{ success: true } | { error: string }> {
  try {
    const accessToken = await getAccessToken()
    if (!accessToken) return { error: 'No access token' }
    await deleteCalendarEvent(accessToken, eventId)
    return { success: true }
  } catch (err) {
    console.error('[syncDeleteFromCalendar]', err)
    return { error: String(err) }
  }
}

export async function syncFetchCalendarEvents(
  timeMin?: string,
  timeMax?: string
): Promise<{ events: SimpleCalendarEvent[] } | { error: string }> {
  try {
    const accessToken = await getAccessToken()
    if (!accessToken) return { error: 'No access token' }
    const rawEvents = await fetchCalendarEvents(accessToken, timeMin, timeMax)
    
    const events: SimpleCalendarEvent[] = rawEvents.map((e) => {
      // Heuristic to detect Google Calendar auto-generated invites or huge texts
      const desc = e.description || ''
      const isAuto =
        desc.length > 200 || 
        desc.includes('<html') || 
        desc.includes('<a href=') || 
        desc.includes('<u>')

      return {
        id: e.id!,
        title: e.summary || 'Sin título',
        description: isAuto ? null : desc,
        date: e.start?.dateTime || e.start?.date || new Date().toISOString(),
        isAutoGenerated: isAuto,
      }
    })

    return { events }
  } catch (err) {
    console.error('[syncFetchCalendarEvents]', err)
    return { error: String(err) }
  }
}
